( Standard subroutines to copy Piet functionality )

: NOT  ( n -- 0 | 1 )
  DUP 0= IF DROP 1 ELSE DROP 0 THEN ;

: GREATER ( n1 n2 -- 0 | 1 )
  > if 1 else 0 then ;

: roll ( depth rolls -- )
    2dup 0< if
        ." Invalid depth" cr
        abort
    then

    2dup 0= if
        2drop 2drop
        exit
    then

    >r >r
    2>r 2>r
    2dup mod swap

    begin
        2dup 0>
    while
        2dup r@ +
        r@ 1- r> swap r> swap pick swap pick swap !
        1- repeat
    drop drop
    2r> 2r> drop drop ;


( THE FOLLOWING CODE WAS GENERATED BY PIET TOOL )
( DO NOT EDIT )

 3 DUP
*
1 +
DUP
*
1 -
DUP
1 1 DROP
1 DROP
1 DROP
1 -
DUP
NOT
DROP
DROP
DUP
NOT
DROP
1 -
DUP
DUP
1 5 3 1 6 4 PIET-ROLL
2 6 3 2 PIET-ROLL
1 +
5 1 3 2 PIET-ROLL
DUP
2 4 3 1 NOT
5 4 PIET-ROLL
2 1 DROP
1 DROP
1 -
DUP
NOT
DROP
1 -
DUP
NOT
DROP
DROP
3 DUP
*
1 +
3 1 PIET-ROLL
DUP
3 DUP
*
4 2 PIET-ROLL
DUP
NOT
DROP
.
DROP
1 DROP
1 DROP
1 -
DUP
NOT
DROP
1 -
DUP
NOT
DROP
1 -
DUP
NOT
DROP
1 -
DUP
NOT
DROP
1 -
DUP
NOT
DROP
1 -
DUP
NOT
DROP
1 -
DUP
NOT
DROP
1 -
DUP
NOT
DROP
1 -
DUP
NOT
DROP
1 -
DUP
NOT
DROP
DROP
3 DUP
*
1 +
DUP
1 +
*
4 DUP
DUP
+
*
EMIT
DUP
1 +
EMIT
DUP
4 DUP
+
-
EMIT
4 DUP
DUP
+
*
EMIT
3 DUP
DROP
DROP
DUP
3 DUP
1 +
*
-
EMIT
DUP
3 DUP
*
-
DUP
EMIT
EMIT
4 +
EMIT
1 1 DROP
DROP
1 DROP
1 DROP
1 -
DUP
NOT
DROP
1 -
DUP
NOT
DROP
1 -
DUP
NOT
DROP
1 -
DUP
NOT
DROP
1 -
DUP
NOT
DROP
1 -
DUP
NOT
DROP
1 -
DUP
NOT
DROP
1 -
DUP
NOT
DROP
1 -
DUP
NOT
DROP
1 -
DUP
NOT
DROP
