( Standard subroutines to copy Piet functionality )

: NOT  ( n -- 0 | 1 )
  DUP 0= IF DROP 1 ELSE DROP 0 THEN ;

: GREATER ( n1 n2 -- 0 | 1 )
  > if 1 else 0 then ;

: PIET_ROLL ( depth rolls -- )
    2dup 0< if
        ." Invalid depth" cr
        abort
    then

    2dup 0= if
        2drop 2drop
        exit
    then

    >r >r
    2>r 2>r
    2dup mod swap

    begin
        2dup 0>
    while
        2dup r@ +
        r@ 1- r> swap r> swap pick swap pick swap !
        1- repeat
    drop drop
    2r> 2r> drop drop ;


( THE FOLLOWING CODE WAS GENERATED BY PIET TOOL )
( DO NOT EDIT )

